### ISSUE TITLE
[FEAT] Main뷰에서 Shake 연결 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [28th-SOPT-iOS-CloneCoding/MiraClone-ShinYoonAh#4]
### 🐌 이슈 내용 
Shake를 하면 Main뷰에서 QR뷰로 이동하도록 구현

### 🌈 TODO 
- [x] MainReactor 생성
- [x] Reactor 기능 구현
- [x] Shake 기능 구현
- [x] Shake 변수 UserDefault로 생성해두기
