### ISSUE TITLE
[FEAT] QR Code 변경 기능 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [28th-SOPT-iOS-CloneCoding/MiraClone-ShinYoonAh#6]
### 🐌 이슈 내용 
count에 따라서 QR Code가 Reload되는 기능 구현

### 🌈 TODO 
- [ ] count 코드 완성
- [ ] count 완료되면 refresh구현
- [ ] 3번의 count 후 멈추기 구현
- [ ] 불러오기로 refresh하기
